#!/bin/bash
# Triton is a program used to easily do...pretty much anything I want.

# =========== SOURCE ===========
source "$(dirname "$0")/config.sh"
source "$(dirname "$0")/helpers.sh"
#source "$(dirname "$0")/themetool.sh"

# =========== FUNCTIONS ============

function usage () {
  echo "Usage: $(basename "$0") themes [ init | set | current | ls ]"
  echo "Commands:"
  echo "  init         | writes a triton.conf file under $HOME/.config/triton/, if it does not already exist."
  echo "  set [theme]  | sets corresponding configs from [theme], if it exists"
  echo "  current      | outputs the current theme to stdout"
  echo "  ls           | lists themes available to set to"
}

# set theme to $1
function try_set_theme () {
  local warn_list=("delete all symlinks referencing ${dir_triton}/current_theme contents" "delete all contents of ${dir_triton}/current_theme" "replace them with those seen in ${dir_themes}/$switchto")
  echo "Performing this action will: "
  for element in "${warn_list[@]}"; do
    echo " - $element"
  done
  if ask "Are you sure you want to do this?"; then
    set_theme $1
  fi
}

# =========== SCRIPT ============

case $1 in
  "--help" | "-h")
    usage; exit 0
    ;;
  "themes")
    source "$(dirname "$0")/themetool.sh"
    case $2 in
      "set")
        if themename_exists "$3"; then
          switchto="$3"
          try_set_theme "$3"
        elif [ -z "$3" ]; then
          error "no theme provided. Use \"$0 themes ls\" to see available themes."
        else
          error "theme \"$3\" does not exist in .themes directory: {dir_themes}.\nUse \"$0 themes ls\" to see available themes."
        fi
        ;;
      "ls")
        list_themes
        ;;
      "current")
        echo "Your current theme is: ${current_theme}"
        ;;
      *)
        usage; exit 1
        ;;
    esac
    ;;
  "init")
    write_config_file
    ;;
  *)
    usage; exit 1
    ;;
esac
